### ISSUE TITLE
global timeout option

### ISSUE THREAD

**Issue by jondruse** [mbleigh/princely#32]
We use princely to create about 10K pdfs per week.  We have some external dependencies (like images) that can be quite slow.  Sometimes prince will work on generating a pdf for > 30 min which is far too long.  

prince has an --http-timeout option but this doesn't work because it can produce mostly empty documents.  So the reasonable answer is to add a timeout block around the call to the prince executable to timeout the entire document.  

I wanted to reach out to you before I went ahead and made the change to see if you have any thoughts on how you would do this, or I can just go for it.

Please feel free to PM me here and we can figure it out.  Talk soon!

**Comment by dmitry** [comment]
Can it be rebased and merged?

**Comment by jondruse** [comment]
Looks like this was added w/o my PR years ago.
