### ISSUE TITLE
get pdf as base64-encoded string?

### ISSUE THREAD

**Issue by peashutop** [mbleigh/princely#43]
I've been happily using prince/princely in a Rails 4 app to render PDFs which can be downloaded in the browser, using a `format.pdf` block in a controller—all as described in the README.

Now I'm looking to construct a PDF in the same way (using a Rails view template), but I want to invoke the pdf creation in a model, not a controller. Instead of emitting the file, I want to capture it as a string in my code, so I can then base64-encode it and pass it off to some unrelated code for further processing.

Can you provide any pointers about how I render the pdf to a string from a model—while still making use of my view? Thanks much!

**Comment by modsognir** [comment]
You can render a PDF from a string with `Princely::Pdf.new.pdf_from_string(string)`

Now you'd just have to find a way to get the template emitted. One way would be to build up a controller and use that directly, eg: https://www.amberbit.com/blog/2011/12/27/render-views-and-partials-outside-controllers-in-rails-3/ (nb: that's for Rails 3, so no guarantees on how accurate it still is).

Another way is to use ERB directly (or Haml::Engine if you're using haml). Example: `ERB.new(File.read(Rails.root.join('app', 'views', 'whatever', 'show.html.erb').result(binding)`

**Comment by peashutop** [comment]
Thanks, @modsognir. I managed to build up a controller with most of what I needed as follows. Then, as you said, the pdf part was easy:

```
controller = ApplicationController.new
controller.request = ActionDispatch::Request.new(foo: "/foo/bar")
html_string = controller.render_to_string(
        template: "/path/to/view/template.html.haml",
        layout: "pdf",
        locals: :@local1 => local1, :@local2 => local2.
    )
prince = Princely.new
prince.pdf_from_string(html_string)
```

The two gotchas that are accounted for above:

1) The Request.new argument needs to be a hash (I am literally using foo: "/foo/bar"). Otherwise, at least on Rails 4.1, actionpack-4.1.1/lib/action_dispatch/http/parameters.rb will break in the #path_parameters method if your view invokes a link helper.

2) The syntax for supplying local variables is easy to get wrong. Credit: http://makandracards.com/makandra/17751-render-a-view-from-a-model-in-rails for this fix.

All of this said, I then hit another snag: some of my views have CanCan-based permissions code, so it seems I need to inject a current_user into the request as well. At this point I'm realizing that I'm basically recreating the entire controller—newing up instance variables for the view, setting a current_user, etc.—and so I think I'm going to abandon this approach, and do something like this instead:

```
session = ActionDispatch::Integration::Session.new(Rails.application)
session.get(path_to_pdf_resource)
encoded_pdf_string = Base64.encode64(session.response.body)
```

```
