### ISSUE TITLE
Is it possible to writer the pdf content  into file instead of generating the pdf view?

### ISSUE THREAD

**Issue by venkatasubbaiah** [mbleigh/princely#47]

**Comment by venkatasubbaiah** [comment]
As per my requirement I have to save it in the S3 instead of showing in view. Please help me.
Thanks in Advance

**Comment by dotdotdotpaul** [comment]
There are a lot of bits of sample code out there for using ActionView without a controller, it works for Princely stuff as well.  Check out the gem RenderAnywhere (https://github.com/yappbox/render_anywhere); I'm currently using that to render to a file with Princely from a background process.

**Comment by modsognir** [comment]
RenderAnywhere is good option if you don't want to delve deeper into ActionView internals. Princely can build a pdf from any string with Princely::Pdf class, but you'll have to render that first with ActionView.
