### ISSUE TITLE
2.0.0 version in RubyGems seems to require 'princely/view_helpers', but file does not exist

### ISSUE THREAD

**Issue by yyyc514** [mbleigh/princely#48]
Can't find this in the repository but I install the gem and there it is.

**Comment by kernow** [comment]
I'm getting the same issue.

`/Users/xxx/.gem/ruby/2.1.2/gems/princely-2.0.0/lib/princely/rails.rb:2:in `require': cannot load such file -- princely/view_helpers (LoadError)
	from /Users/xxx/.gem/ruby/2.1.2/gems/princely-2.0.0/lib/princely/rails.rb:2:in `<top (required)>'
	from /Users/xxx/.gem/ruby/2.1.2/gems/princely-2.0.0/lib/princely.rb:19:in `require'
	from /Users/xxx/.gem/ruby/2.1.2/gems/princely-2.0.0/lib/princely.rb:19:in `<top (required)>'
	from /Users/xxx/.gem/ruby/2.1.2/gems/bundler-1.12.4/lib/bundler/runtime.rb:86:in `require'
	from /Users/xxx/.gem/ruby/2.1.2/gems/bundler-1.12.4/lib/bundler/runtime.rb:86:in `block (2 levels) in require'
	from /Users/xxx/.gem/ruby/2.1.2/gems/bundler-1.12.4/lib/bundler/runtime.rb:81:in `each'
	from /Users/xxx/.gem/ruby/2.1.2/gems/bundler-1.12.4/lib/bundler/runtime.rb:81:in `block in require'
	from /Users/xxx/.gem/ruby/2.1.2/gems/bundler-1.12.4/lib/bundler/runtime.rb:70:in `each'
	from /Users/xxx/.gem/ruby/2.1.2/gems/bundler-1.12.4/lib/bundler/runtime.rb:70:in `require'
	from /Users/xxx/.gem/ruby/2.1.2/gems/bundler-1.12.4/lib/bundler.rb:102:in `require'
	from /Users/xxx/Projects/xxx/web/config/application.rb:6:in `<top (required)>'
	from /Users/xxx/.gem/ruby/2.1.2/gems/railties-4.1.15/lib/rails/commands/commands_tasks.rb:79:in `require'
	from /Users/xxx/.gem/ruby/2.1.2/gems/railties-4.1.15/lib/rails/commands/commands_tasks.rb:79:in `block in server'
	from /Users/xxx/.gem/ruby/2.1.2/gems/railties-4.1.15/lib/rails/commands/commands_tasks.rb:76:in `tap'
	from /Users/xxx/.gem/ruby/2.1.2/gems/railties-4.1.15/lib/rails/commands/commands_tasks.rb:76:in `server'
	from /Users/xxx/.gem/ruby/2.1.2/gems/railties-4.1.15/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
	from /Users/xxx/.gem/ruby/2.1.2/gems/railties-4.1.15/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'`

**Comment by modsognir** [comment]
Seems there were some development files included in the build, i've pushed 2.0.2 with a clean build
