### ISSUE TITLE
Help trying to set conformance profile for PDF's 

### ISSUE THREAD

**Issue by fedesc** [mbleigh/princely#50]
Hi i'm using a Ruby on Rails application with princely to convert HTML to PDF. 
Where can i set that all pdfs will be PDF/A-1b as default? 
How can i truly validate that it's compliant ?

**Comment by modsognir** [comment]
This is more of a PrinceXML question. From the look of [their forums](http://www.princexml.com/forum/topic/1136/how-do-i-create-a-pdf-a-1a-compliant-pdf-using-prince-xml) it seems that all docs are PDF/A-1b compliant.
