### ISSUE TITLE
Release with rails 5.1 fix (deprecated alias_method_chain)

### ISSUE THREAD

**Issue by dmitry** [mbleigh/princely#59]
Please release new version to the rubygems with a rails 5.1 fix (without `alias_method_chain`).

**Comment by brian4d** [comment]
I submitted a pull request on May 15 that fixes this issue. Unfortunately, @mbleigh hasn't responded.

**Comment by modsognir** [comment]
2.1.0 is released with @brian4d's changes. Sorry for the delay.
